name : dot net testing

on : 
  push : 
    branches :
    - main 
  workflow_dispatch :

defaults :
  run :
    working-directory : 'D:\Documents\Downloads\dotnet-sdk-6.0.124-win-x86'

jobs:
  dot-net:
    runs-on: self-hosted

    steps:
      - name: checkout stage
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.124

      - name: Restore dependencies
        run: dotnet restore dotnet-hello-world.sln

      - name: Display dotnet version
        run: dotnet --version
        
      -  name : build
         run : dotnet restore ./dotnet-hello-world.sln
