name : dot net testing

on : 
  push : 
    branches :
    - main 
  workflow_dispatch :

defaults :
  run :
    working-directory : 'D:\Documents\Downloads\dotnet-sdk-6.0.124-win-x86'

jobs :
  dot-net :
    runs-on : self-hosted 

    steps :
    - name : checkout stage
      uses: actions/checkout@v2

    # - name : change dir
    #   run : cd 'D:\test'

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      # with:
      #   dotnet-version:  5.0
    # - name : chekc ir
    #   run : ${{ github.workspace }}


    # - name: .NET Restore
    #   uses: zyactions/dotnet-restore@v1
    #   with:
    #     workspace: dotnet-hello-world.sln

    # - run : cd 'D:\Documents\Downloads\dotnet-sdk-6.0.124-win-x86'
        
    - name : Restore dependencies 
      run : |
          # dotnet restore --locked-mode
          cd 'D:\Documents\Downloads\dotnet-sdk-6.0.124-win-x86\'
          # D:\Documents\Downloads\dotnet-sdk-6.0.124-win-x86\dotnet restore dotnet-hello-world.sln

          dotnet restore 'D:\Desktop\dotty\_work\dot-net\dot-net\dotnet-hello-world.sln'

    - name : Display dotnet version
      run : dotnet --version

    - name : build
      run : dotnet build dotnet-hello-world.sln
